version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    working_directory: ~/twks
    steps:
      - checkout
      - restore_cache:
          key: twks-{{ checksum "java/pom.xml" }}-{{ checksum "java/cli/pom.xml" }}-{{ checksum "java/core/pom.xml" }}-{{ checksum "java/server/pom.xml" }}
      - run:
          name: Build and test the Java library
          command: cd java && script/test
      - save_cache:
          key: twks-{{ checksum "java/pom.xml" }}-{{ checksum "java/cli/pom.xml" }}-{{ checksum "java/core/pom.xml" }}-{{ checksum "java/server/pom.xml" }}
          paths:
            - ~/.m2
      - run: mkdir test-results
      - run: mv java/core/target/surefire-reports test-results/java
      - setup_remote_docker
      - run:
          name: Build Docker images
          command: cd .circleci && docker-compose -f docker-compose-ci.yml build
      - run:
          name: Push server Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              cd .circleci && docker-compose -f docker-compose-ci.yml push twks-server
            fi
      - run:
          name: Run the server
          command: cd .circleci && docker-compose -f docker-compose-ci.yml up -d
      - run:
          name: Curl the server until it comes up
          command: docker exec twks-py bash -c "curl --retry-connrefused --retry 90 --retry-delay 1 http://twks-server:8080"
      - run:
          name: Run Python tests
          command: |
            mkdir -p test-results/py
            docker exec twks-py bash -c "mkdir -p ../test-results/py && cd tests && TWKS_BASE_URL=\"http://twks-server:8080\" pytest --junitxml=../../test-results/py/junit.xml"
            docker cp twks-py:/twks/test-results/py/junit.xml test-results/py

      - store_test_results:
          path: test-results
