version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: twdb-{{ checksum "java/pom.xml" }}-{{ checksum "java/api/pom.xml" }}-{{ checksum "java/cli/pom.xml" }}-{{ checksum "java/lib/pom.xml" }}-{{ checksum "java/server/pom.xml" }}
      - run: cd java && mvn package
      - save_cache:
          key: twdb-{{ checksum "java/pom.xml" }}-{{ checksum "java/api/pom.xml" }}-{{ checksum "java/cli/pom.xml" }}-{{ checksum "java/lib/pom.xml" }}-{{ checksum "java/server/pom.xml" }}
          paths:
            - ~/.m2
      - store_test_results:
          path: java/target/surefire-reports
#      - store_artifacts:
#          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
