version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    working_directory: ~/twks
    steps:
      - checkout
      - restore_cache:
          key: twks-{{ checksum "java/pom.xml" }}-{{ checksum "java/abc/pom.xml" }}-{{ checksum "java/api/pom.xml" }}-{{ checksum "java/cli/pom.xml" }}-{{ checksum "java/client/pom.xml" }}-{{ checksum "java/ext/pom.xml" }}-{{ checksum "java/factory/pom.xml" }}-{{ checksum "java/nanopub/pom.xml" }}-{{ checksum "java/server/pom.xml" }}-{{ checksum "java/tdb/pom.xml" }}-{{ checksum "java/test/pom.xml" }}-{{ checksum "java/uri/pom.xml" }}-{{ checksum "java/vocabulary/pom.xml" }}
      - run:
          name: Build and test Java modules
          command: |
            cd java
            MAVEN_OPTS="-Xmx3500M" mvn -q clean package install site site:stage -DstagingDirectory=$PWD/site
            tar cf site.tar site
            bzip2 -9 site.tar
            cd ..
            mkdir -p test-results/java
            mv java/cli/target/surefire-reports/* test-results/java
            mv java/ext/target/surefire-reports/* test-results/java
            mv java/factory/target/surefire-reports/* test-results/java
            mv java/nanopub/target/surefire-reports/* test-results/java
            mv java/server/target/surefire-reports/* test-results/java
            mv java/tdb/target/surefire-reports/* test-results/java
            mv java/uri/target/surefire-reports/* test-results/java
      - store_artifacts:
          path: java/site.tar.bz2
      - run:
          name: Build Java examples
          command: |
            cd java/examples/client
            mvn package
      - save_cache:
          key: twks-{{ checksum "java/pom.xml" }}-{{ checksum "java/abc/pom.xml" }}-{{ checksum "java/api/pom.xml" }}-{{ checksum "java/cli/pom.xml" }}-{{ checksum "java/client/pom.xml" }}-{{ checksum "java/ext/pom.xml" }}-{{ checksum "java/factory/pom.xml" }}-{{ checksum "java/nanopub/pom.xml" }}-{{ checksum "java/server/pom.xml" }}-{{ checksum "java/tdb/pom.xml" }}-{{ checksum "java/test/pom.xml" }}-{{ checksum "java/uri/pom.xml" }}-{{ checksum "java/vocabulary/pom.xml" }}
          paths:
            - ~/.m2
      - setup_remote_docker
      - run:
          name: Copy .m2 directory to java/ temporarily so that it will be speed up Docker image builds
          command: cp -p -R ~/.m2 java/
      - run:
          name: Build Docker images
          command: cd docker && docker-compose build
      - run:
          name: Run the server
          command: cd docker && docker-compose up -d twks-java twks-py twks-server
      - run:
          name: Curl the server until it comes up
          command: docker exec twks-py bash -c "curl --retry-connrefused --retry 90 --retry-delay 1 http://twks-server:8080"
      - run:
          name: Run Java client tests
          command: |
            docker exec twks-java bash -c "mvn -q -DargLine=\"-Dtwks.serverBaseUrl=http://twks-server:8080\" -Dtwks-client.skipTests=false test"
            docker cp twks-java:/twks/java/client/target/surefire-reports/TEST-edu.rpi.tw.twks.client.TwksClientTest.xml test-results/java
      - run:
          name: Run Python client tests
          command: |
            mkdir -p test-results/py
            docker exec twks-py bash -c "mkdir -p ../test-results/py && cd tests && TWKS_SERVER_BASE_URL=\"http://twks-server:8080\" pytest --junitxml=../../test-results/py/junit.xml"
            docker cp twks-py:/twks/test-results/py/junit.xml test-results/py
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results
      - run:
          name: Push Docker images
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              cd docker && docker-compose push twks-cli twks-server
            fi
      - run:
          name: Push Java artifacts
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cp ~/twks/.circleci/maven-settings.xml ~/.m2/settings.xml
              echo -e "$OSSRH_GPG_KEY" | gpg --import
              cd java && mvn -q -P release -Dmaven.test.skip=true deploy
            fi
  lint_md:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/twks
    steps:
      - checkout
      - run: .circleci/lint-md.sh
      - store_artifacts:
          path: lint-results
workflows:
  version: 2
  build:
    jobs:
      - build
      - lint_md
