version: '3'
services:
  twks-py:
    build:
      context: ..
      dockerfile: .circleci/Dockerfile-twks-py
    container_name: "twks-py"
  twks-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: "twks-server"
    image: tetherlessworld/twks-server
    ports:
      - "8080:8080"
