version: '3'
services:
  twks-cli:
    build:
      context: ..
      dockerfile: docker/cli/Dockerfile
    container_name: "twks-cli"
    image: tetherlessworld/twks-cli
    links:
      - twks-server
  twks-java:
    build:
      context: ..
      dockerfile: .circleci/Dockerfile-twks-java
    container_name: "twks-java"
  twks-py:
    build:
      context: ..
      dockerfile: .circleci/Dockerfile-twks-py
    container_name: "twks-py"
  twks-server:
    build:
      context: ..
      dockerfile: docker/server/Dockerfile
    container_name: "twks-server"
    image: tetherlessworld/twks-server
    ports:
      - "8080:8080"
