version: '3'
services:
  twdb-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: "twdb-server"
    image: tetherlessworld/twdb-server
    ports:
      - "8080:8080"
    volumes:
      - twdb-data:/data

volumes:
  twdb-data:
