version: '3'
services:
  twks-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: "twks-server"
    image: tetherlessworld/twks-server
    ports:
      - "8080:8080"
    volumes:
      - twks-data:/data

volumes:
  twks-data:
