version: "3.5"
networks:
  twks:
    name: twks
services:
  twks-server:
    build:
      context: ../../..
      dockerfile: docker/image/server/Dockerfile
    container_name: "twks-server"
    image: tetherlessworld/twks-server
    networks:
      - twks
